/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.CGPaint;

import CGPaintForm.Interface;
import javax.swing.SwingUtilities;

public class App {

    public static void main(String[] args) {
   
        SwingUtilities.invokeLater(() -> {
            Interface myInterface = new Interface();
            myInterface.setVisible(true); // make GUI visible
        });
    }
}
